kind: pipeline
name: default

steps:
- name: download  
  image: plugins/download
  settings:
    source: https://webplus-cn-shenzhen.oss-cn-shenzhen.aliyuncs.com/cli/install.sh
  commands:
    - echo install.sh
