kind: pipeline
type: docker
name: default

steps:
- name: build
  image: mcr.microsoft.com/dotnet/sdk:3.1
  commands:
    - dotnet publish -c:Release -o ./publish
- name: deploy
  image: jakeuj/aliwpctl
  environment:
    ALIYUN_ACCESS_KEY_ID:
      from_secret: aliyun_access_key_id
    ALIYUN_ACCESS_KEY_SECRET:
      from_secret: aliyun_access_key_secret
    LINE_TOKEN:
      from_secret: line_token
  commands:
    - zip -r webplusdemo.zip ./publish
    - wpctl configure --access-key-id $ALIYUN_ACCESS_KEY_ID --access-key-secret $ALIYUN_ACCESS_KEY_SECRET --region cn-shanghai --profile demo
    - wpctl env:apply --package webplusdemo.zip --label ${DRONE_COMMIT_SHA:0:8} --env Test --app Test -q
    - 'curl https://notify-api.line.me/api/notify -X POST -F "message=Willy is great!" -H "Authorization: Bearer $LINE_TOKEN"'
