kind: pipeline
type: docker
name: default

steps:
- name: line
  environment:
    LINE_TOKEN:
      from_secret: line_token
  commands:
    - "curl https://notify-api.line.me/api/notify -X POST -F 'message=Test' -H 'Authorization: Bearer $LINE_TOKEN' --trace-ascii debugdump.txt -v"
    - cat debugdump.txt
- name: build
  image: mcr.microsoft.com/dotnet/sdk:3.1
    - dotnet publish -c:Release -o ./publish
- name: deploy
  image: jakeuj/aliwpctl
  environment:
    ALIYUN_ACCESS_KEY_ID:
      from_secret: aliyun_access_key_id
    ALIYUN_ACCESS_KEY_SECRET:
      from_secret: aliyun_access_key_secret
  commands:
    - zip -r webplusdemo.zip ./publish
    - wpctl configure --access-key-id $ALIYUN_ACCESS_KEY_ID --access-key-secret $ALIYUN_ACCESS_KEY_SECRET --region cn-shanghai --profile demo
    - wpctl env:apply --package webplusdemo.zip --label ${DRONE_COMMIT_SHA:0:8} --env Test --app Test -q
