kind: pipeline
name: dev_depoly
workspace:
  base: /data/netcore
  path: istr
  
steps:
- name: build
  image: mcr.microsoft.com/dotnet/sdk:3.1
  commands:
    - dotnet publish -c:Release -o ./publish
    - echo '>>> 建置完成，顯示一下結果看看，威力 Boy.'
    - ls -la
