kind: pipeline
name: dev_depoly
workspace:
  base: /data/netcore
  path: istr
  
steps:
- name: download  
  image: plugins/download
  settings:
    source: https://webplus-cn-shenzhen.oss-cn-shenzhen.aliyuncs.com/cli/install.sh
  secrets: [ aliyun_access_key_id,aliyun_access_key_secret]
  commands:
    - source install.sh
    - wpctl configure --access-key-id "$${ALIYUN_ACCESS_KEY_ID}" --access-key-secret "$${ALIYUN_ACCESS_KEY_SECRET}" --region "cn-shanghai" --profile demo
    
steps:
- name: build
  image: mcr.microsoft.com/dotnet/sdk:3.1
  secrets: [ aliyun_access_key_id,aliyun_access_key_secret]
  commands:
    - echo "autoload bashcompinit \nbashcompinit" >> ~/.zshrc
    - cat ~/.zshrc
    - apt-get update -y
    - apt-get install zip -y
    - apt-get install bash -y
    - eval "$(curl -s -L https://webplus-cn-shenzhen.oss-cn-shenzhen.aliyuncs.com/cli/install.sh)"
    - wpctl configure --access-key-id "$${ALIYUN_ACCESS_KEY_ID}" --access-key-secret "$${ALIYUN_ACCESS_KEY_SECRET}" --region "cn-shanghai" --profile demo
    - dotnet publish -c:Release -o ./publish
    - zip -r webplusdemo.zip ./publish
    - wpctl env:apply --package webplusdemo.zip --label webplusVersion0.2 --env Test --app Test -q
